spring.application.name=develop


# MYSQL
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.url=jdbc:mariadb://localhost:3306/board


# ORACLE
# IP:PORT:SID
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.datasource.username=study
spring.datasource.password=8839
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
