spring.application.name=develop


# MYSQL
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.url=jdbc:mariadb://localhost:3306/study
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# camel ? -? ??
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# ORACLE
#IP:PORT:SID
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
#spring.datasource.username=study
#spring.datasource.password=oracle
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
